# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  name: MYLOCALPOOL  # Make sure this is a valid agent pool name

steps:
  # Step 1: Build the project with Maven
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
    displayName: 'Build with Maven'

  # Step 2: Simulate Deployment with File Existence Check
  - script: |
      echo "Simulating deployment..."
      dir target
      if exist target\*.jar (
        echo "JAR found. Proceeding with deployment..."
        mkdir deployed
        copy target\*.jar deployed\
        echo "Deployment successful!"
      ) else (
        echo "ERROR: No JAR file found in target directory"
        exit /b 1
      )
    displayName: 'Simulate Deployment'

  # Step 3: Verify Deployment Output
  - script: |
      echo "Contents of deployed folder:"
      dir deployed
    displayName: 'Verify Deployment Output'

